version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
